/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package programming.basics;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class ArrayOperationsTest {
    @Test void appHasAGreeting() {
        ArrayOperations classUnderTest = new ArrayOperations();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
